"""Adds name column in Jobseeker model

Revision ID: 0b41f4f96d92
Revises: 5a747a27fe2b
Create Date: 2024-08-15 22:34:05.863273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b41f4f96d92'
down_revision = '5a747a27fe2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseekers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseekers', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
