"""Adds job category to Jobseeker

Revision ID: 5a747a27fe2b
Revises: 9aa2f6f276dd
Create Date: 2024-08-12 10:50:54.316666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a747a27fe2b'
down_revision = '9aa2f6f276dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseekers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_category', sa.String(), nullable=True))
        batch_op.drop_constraint('fk_jobseekers_job_category_id_jobcategories', type_='foreignkey')
        batch_op.drop_column('job_category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseekers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_jobseekers_job_category_id_jobcategories', 'jobcategories', ['job_category_id'], ['id'])
        batch_op.drop_column('job_category')

    # ### end Alembic commands ###
