"""Removes fileupload FK from jobseekers table

Revision ID: 848e2ebaa0dd
Revises: 
Create Date: 2024-08-06 22:56:45.738302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848e2ebaa0dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('_password_hash', sa.String(length=128), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_admins_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('company_profile', sa.String(), nullable=True),
    sa.Column('verification_status', sa.Boolean(), nullable=True),
    sa.Column('contact_details', sa.String(), nullable=True),
    sa.Column('pay_to_view', sa.Boolean(), nullable=True),
    sa.Column('history', sa.String(), nullable=True),
    sa.Column('services_offered', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_employers_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobseekers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prof_pic', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('job_category_id', sa.Integer(), nullable=True),
    sa.Column('salary_expectation', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.Boolean(), nullable=True),
    sa.Column('work_experience', sa.Text(), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_category_id'], ['jobcategories.id'], name=op.f('fk_jobseekers_job_category_id_jobcategories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_jobseekers_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contactrequests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.Column('jobseeker_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], name=op.f('fk_contactrequests_employer_id_employers')),
    sa.ForeignKeyConstraint(['jobseeker_id'], ['jobseekers.id'], name=op.f('fk_contactrequests_jobseeker_id_jobseekers')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fileuploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobseeker_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jobseeker_id'], ['jobseekers.id'], name=op.f('fk_fileuploads_jobseeker_id_jobseekers')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], name=op.f('fk_payments_employer_id_employers')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('fileuploads')
    op.drop_table('contactrequests')
    op.drop_table('jobseekers')
    op.drop_table('employers')
    op.drop_table('admins')
    op.drop_table('users')
    op.drop_table('jobcategories')
    # ### end Alembic commands ###
